apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-vault-0
  annotations:
    argocd.argoproj.io/sync-options: Delete=false,Prune=false
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/component: data
    app.kubernetes.io/name: vault
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: openebs-lvm
