apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: vault
spec:
  hosts:
    - vault.ultary.co
  gateways:
    - istio-gateways/ultary-core
  http:
    - route:
        - destination:
            host: vault.vault.svc.cluster.local
            port:
              number: 8200
---
