apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: vault
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  hosts:
    - vault.ghilbut.com
  gateways:
    - istio-gateways/private
  http:
    - route:
        - destination:
            host: vault-active.vault.svc.cluster.local
            port:
              number: 8200
