apiVersion: v1
kind: Namespace
metadata:
  name: argo
  annotations:
    argocd.argoproj.io/sync-options: Delete=false,Prune=false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo
  namespace: argo
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  project: default
  sources:
    - chart: argo-cd
      repoURL: https://argoproj.github.io/argo-helm/
      targetRevision: 10.2.2
      helm:
        releaseName: cd
        valueFiles:
          - values.yaml
        values: |
          fullnameOverride: cd
          global:
            logging: 
              level: warn
          configs:
            cm:
              users.anonymous.enabled: true
              application.resourceTrackingMethod: annotation+label
              installationID: blue
              admin.enabled: false
              resource.customizations.ignoreDifferences.all: |
                jsonPointers:
                  - /metadata/annotations/argocd.argoproj.io~1installation-id
                  - /metadata/annotations/argocd.argoproj.io~1tracking-id
                  - /metadata/labels/argocd.argoproj.io~1instance
            params:
              applicationsetcontroller.enable.progressive.syncs: true
              server.insecure: true
              server.basehref: cd
              server.rootpath: cd
            rbac:
              policy.default: role:admin
            secret:
              createSecret: false
          dex:
            enabled: false
    - path: apps/argo-apps/argo/
      repoURL: https://github.com/ghilbut/platform.git
      targetRevision: main
  destination:
    name: in-cluster
    namespace: argo
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - Validate=true
