apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ebs
  namespace: argo
spec:
  project: default
  sources:
    - chart: lvm-localpv
      repoURL: https://openebs.github.io/lvm-localpv
      targetRevision: 1.9.1
      helm:
        releaseName: ebs
        values: |
          analytics:
            enabled: false
          crds:
            enabled: true
    - path: apps/argo-apps/ebs
      repoURL: https://github.com/ghilbut/platform.git
      targetRevision: main
  destination:
    name: in-cluster
    namespace: ebs
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - ServerSideApply=true
      - Validate=true
