apiVersion: v1
kind: Namespace
metadata:
  name: ebs
  annotations:
    argocd.argoproj.io/sync-options: Delete=false,Prune=false
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-lvm
  annotations:
    argocd.argoproj.io/sync-wave: "1"
provisioner: local.csi.openebs.io
allowVolumeExpansion: true
parameters:
  storage: lvm
  volgroup: openebs
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ebs
  namespace: argo
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    chart: lvm-localpv
    repoURL: https://openebs.github.io/lvm-localpv
    targetRevision: 1.9.1
    helm:
      releaseName: openebs-lvm
  destination:
    name: in-cluster
    namespace: ebs
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - ServerSideApply=true
      - Validate=true
