apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argo
spec:
  project: default
  sources:
    - chart: external-dns
      repoURL: https://kubernetes-sigs.github.io/external-dns
      targetRevision: 1.21.1
      helm:
        releaseName: external-dns-public
        values: |
          env:
            - name: AWS_EC2_METADATA_DISABLED
              value: "true"
            - name: AWS_REGION
              value: us-east-1
            - name: AWS_ROLE_ARN
              value: arn:aws:iam::869061964712:role/platform-cpa-external-dns
            - name: AWS_WEB_IDENTITY_TOKEN_FILE
              value: /var/run/secrets/aws-iam-token/token
          extraVolumeMounts:
            - mountPath: /var/run/secrets/aws-iam-token
              name: aws-iam-token
              readOnly: true
          extraVolumes:
            - name: aws-iam-token
              projected:
                sources:
                  - serviceAccountToken:
                      audience: sts.amazonaws.com
                      expirationSeconds: 3600
                      path: token
          logLevel: info
          managedRecordTypes:
            - CNAME
          policy: sync
          podSecurityContext:
            fsGroup: 65534
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          provider: aws
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 65532
            runAsNonRoot: true
            runAsUser: 65532
            seccompProfile:
              type: RuntimeDefault
          domainFilters:
            - ghilbut.com
            - ghilbut.net
          annotationFilter: external-dns.alpha.kubernetes.io/target=ghilbut.asuscomm.com
          registry: txt
          serviceAccount:
            create: true
            name: external-dns-public
          sources:
            - istio-gateway
          txtOwnerId: external-dns-cpa
          txtPrefix: external-dns-
    - chart: external-dns
      repoURL: https://kubernetes-sigs.github.io/external-dns
      targetRevision: 1.21.1
      helm:
        releaseName: external-dns-private
        values: |
          annotationFilter: external-dns.alpha.kubernetes.io/target=192.168.254.4
          domainFilters:
            - ghilbut.com
            - ghilbut.net
          env:
            - name: ETCD_URLS
              value: http://etcd.coredns.svc.cluster.local:2379
          extraArgs:
            coredns-strictly-owned: true
          logLevel: info
          managedRecordTypes:
            - A
          policy: sync
          podSecurityContext:
            fsGroup: 65534
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          provider: coredns
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 65532
            runAsNonRoot: true
            runAsUser: 65532
            seccompProfile:
              type: RuntimeDefault
          serviceAccount:
            create: true
            name: external-dns-private
          sources:
            - istio-gateway
          txtOwnerId: external-dns-cpa-private
          txtPrefix: external-dns-private-
    - path: apps/argo-apps/external-dns
      repoURL: https://github.com/ghilbut/platform.git
      targetRevision: main
  destination:
    name: in-cluster
    namespace: external-dns
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - ServerSideApply=true
      - Validate=true
