apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  annotations:
    argocd.argoproj.io/sync-options: Delete=false,Prune=false
    argocd.argoproj.io/sync-wave: "-3"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argo
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: default
  sources:
    - chart: base
      repoURL: https://istio-release.storage.googleapis.com/charts
      targetRevision: 1.30.3
      helm:
        releaseName: base
        valueFiles:
          - values.yaml
    - chart: istiod
      repoURL: https://istio-release.storage.googleapis.com/charts
      targetRevision: 1.30.3
      helm:
        releaseName: istiod
        valueFiles:
          - values.yaml
        values: |
          sidecarInjectorWebhook:
            enableNamespacesByDefault: true
  destination:
    name: in-cluster
    namespace: istio-system
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - ServerSideApply=true
      - Validate=true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: istio-validator-istio-system
      jsonPointers:
        - /webhooks/0/failurePolicy
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: istiod-default-validator
      jsonPointers:
        - /webhooks/0/failurePolicy
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-egress
  annotations:
    argocd.argoproj.io/sync-options: Delete=false,Prune=false
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-egress
  namespace: argo
spec:
  project: default
  source:
    chart: gateway
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.30.3
    helm:
      releaseName: egw
      values: |
        service:
          type: ClusterIP
  destination:
    name: in-cluster
    namespace: istio-egress
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - ServerSideApply=true
      - Validate=true
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-gateways
  annotations:
    argocd.argoproj.io/sync-options: Delete=false,Prune=false
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-gateways
  namespace: argo
spec:
  project: default
  sources:
    - chart: gateway
      repoURL: https://istio-release.storage.googleapis.com/charts
      targetRevision: 1.30.3
      helm:
        releaseName: igw
        values: |
          name: istio-ingressgateway
          labels:
            app: istio-ingressgateway
            istio: ingressgateway
          service:
            ports:
              - name: http2
                port: 80
                protocol: TCP
                targetPort: 80
              - name: https
                port: 443
                protocol: TCP
                targetPort: 443
    - path: apps/argo-apps/istio
      repoURL: https://github.com/ghilbut/platform.git
      targetRevision: main
      directory:
        recurse: true
  destination:
    name: in-cluster
    namespace: istio-gateways
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - ServerSideApply=true
      - Validate=true
