apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argo
spec:
  project: default
  sources:
    - chart: vault
      repoURL: https://helm.releases.hashicorp.com
      targetRevision: 0.34.0
      helm:
        releaseName: vault
        values: |
          global:
            tlsDisable: true
          injector:
            enabled: false
          server:
            serviceAccount:
              create: false
              name: vault
            ha:
              enabled: true
              replicas: 1
              raft:
                enabled: true
                setNodeId: true
            dataStorage:
              enabled: true
              size: 10Gi
              storageClass: openebs-lvm
            persistentVolumeClaimRetentionPolicy:
              whenDeleted: Retain
              whenScaled: Retain
            extraEnvironmentVars:
              AWS_EC2_METADATA_DISABLED: "true"
              AWS_REGION: us-east-1
              AWS_ROLE_ARN: arn:aws:iam::869061964712:role/platform-vault
              AWS_WEB_IDENTITY_TOKEN_FILE: /var/run/secrets/aws-iam-token/token
              VAULT_AWSKMS_SEAL_KEY_ID: alias/platform-vault
              VAULT_SEAL_TYPE: awskms
            volumes:
              - name: aws-iam-token
                projected:
                  sources:
                    - serviceAccountToken:
                        audience: sts.amazonaws.com
                        expirationSeconds: 3600
                        path: token
            volumeMounts:
              - mountPath: /var/run/secrets/aws-iam-token
                name: aws-iam-token
                readOnly: true
    - path: apps/argo-apps/vault
      repoURL: https://github.com/ghilbut/platform.git
      targetRevision: main
      directory:
        recurse: true
  destination:
    name: in-cluster
    namespace: vault
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - ServerSideApply=true
      - Validate=true
---
