apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argo
spec:
  project: default
  sources:
    - chart: vault
      repoURL: https://helm.releases.hashicorp.com
      targetRevision: 0.34.0
      helm:
        releaseName: vault
        skipTests: true
        values: |
          global:
            tlsDisable: true
          injector:
            enabled: false
          server:
            updateStrategyType: RollingUpdate
            serviceAccount:
              create: false
              name: vault
            authDelegator:
              enabled: true
            statefulSet:
              annotations:
                argocd.argoproj.io/sync-wave: "2"
              securityContext:
                pod:
                  runAsNonRoot: true
                  runAsGroup: 1000
                  runAsUser: 100
                  fsGroup: 1000
                  seccompProfile:
                    type: RuntimeDefault
                container:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                      - ALL
            ha:
              enabled: true
              replicas: 1
              apiAddr: https://vault.ghilbut.com
              raft:
                enabled: true
                setNodeId: true
                config: |
                  ui = true
                  disable_mlock = true

                  listener "tcp" {
                    tls_disable = 1
                    address = "[::]:8200"
                    cluster_address = "[::]:8201"
                  }

                  seal "awskms" {
                    region = "us-east-1"
                    kms_key_id = "alias/vault-unseal"
                  }

                  storage "raft" {
                    path = "/vault/data"
                  }

                  service_registration "kubernetes" {}
              disruptionBudget:
                enabled: false
            dataStorage:
              enabled: true
              size: 10Gi
              storageClass: openebs-lvm-thin
              accessMode: ReadWriteOnce
            persistentVolumeClaimRetentionPolicy:
              whenDeleted: Retain
              whenScaled: Retain
            readinessProbe:
              enabled: true
              path: /v1/sys/health?standbyok=true&uninitcode=204
            livenessProbe:
              enabled: true
              path: /v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204
              initialDelaySeconds: 60
            extraEnvironmentVars:
              AWS_EC2_METADATA_DISABLED: "true"
              AWS_REGION: us-east-1
              AWS_ROLE_ARN: arn:aws:iam::954066442429:role/vault-cpa-unseal
              AWS_WEB_IDENTITY_TOKEN_FILE: /var/run/secrets/aws-iam-token/token
            volumes:
              - name: aws-iam-token
                projected:
                  defaultMode: 420
                  sources:
                    - serviceAccountToken:
                        audience: sts.amazonaws.com
                        expirationSeconds: 3600
                        path: token
              - name: kubernetes-api-access
                projected:
                  defaultMode: 420
                  sources:
                    - serviceAccountToken:
                        expirationSeconds: 3600
                        path: token
                    - configMap:
                        name: kube-root-ca.crt
                        items:
                          - key: ca.crt
                            path: ca.crt
                    - downwardAPI:
                        items:
                          - path: namespace
                            fieldRef:
                              fieldPath: metadata.namespace
            volumeMounts:
              - mountPath: /var/run/secrets/aws-iam-token
                name: aws-iam-token
                readOnly: true
              - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
                name: kubernetes-api-access
                readOnly: true
    - path: apps/argo-apps/vault
      repoURL: https://github.com/ghilbut/platform.git
      targetRevision: main
      directory:
        recurse: true
  destination:
    name: in-cluster
    namespace: vault
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
      - ServerSideApply=true
      - Validate=true
