apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: private
  annotations:
    external-dns.alpha.kubernetes.io/target: 192.168.254.4
    external-dns.alpha.kubernetes.io/ttl: "300"
    argocd.argoproj.io/sync-wave: "3"
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - id.ghilbut.com
        - argo.ghilbut.com
        - vault.ghilbut.com
      port:
        name: http
        number: 80
        protocol: HTTP
      tls:
        httpsRedirect: true
    - hosts:
        - id.ghilbut.com
        - argo.ghilbut.com
        - vault.ghilbut.com
      port:
        name: https
        number: 443
        protocol: HTTPS
      tls:
        credentialName: ingress-https-tls
        mode: SIMPLE
