apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: public
  namespace: istio-gateways
  annotations:
    external-dns.alpha.kubernetes.io/target: ghilbut.asuscomm.com
    external-dns.alpha.kubernetes.io/ttl: "300"
    argocd.argoproj.io/sync-wave: "2"
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - id.ghilbut.com
        - vault.ghilbut.com
      port:
        name: http
        number: 80
        protocol: HTTP
      tls:
        httpsRedirect: true
    - hosts:
        - id.ghilbut.com
        - vault.ghilbut.com
      port:
        name: https
        number: 443
        protocol: HTTPS
      tls:
        credentialName: public-https-tls
        mode: SIMPLE
