---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: aws-route53
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"
spec:
  acme:
    email: ghilbut@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - selector:
          dnsZones:
            - ghilbut.com
            - ghilbut.net
        dns01:
          route53:
            region: us-east-1
            role: arn:aws:iam::869061964712:role/domains-cpa-cert-manager
            auth:
              kubernetes:
                serviceAccountRef:
                  audiences:
                    - sts.amazonaws.com
                  name: cert-manager
