apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: ultary-argo-vs
spec:
  hosts:
    - argo.ultary.co
  gateways:
    - istio-gateways/ultary-core
  http:
    - match:
        - uri:
            exact: /cd
        - uri:
            prefix: /cd/
      route:
        - destination:
            host: cd-server.argo.svc.cluster.local
            port:
              number: 80
---
# AuthorizationPolicy should be applied to ingress instance directly
# You can't apply to Gateway manifest
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: ultary-core-argo-internet-facing
  namespace: istio-gateways
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  action: ALLOW
  rules:
    - to:
        - operation:
            hosts:
              - argo.ultary.co
              - argo.ultary.co:*
            methods:
              - POST
            paths:
              - /cd/api/webhook
              - /cd/api/webhook/*
---
