apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: argo
spec:
  hosts:
    - argo.ghilbut.com
  gateways:
    - istio-gateways/private
  http:
    - match:
        - uri:
            exact: /
      redirect:
        uri: /cd/
    - match:
        - uri:
            exact: /cd
        - uri:
            prefix: /cd/
      route:
        - destination:
            host: cd-server.argo.svc.cluster.local
            port:
              number: 80
    - match:
        - uri:
            prefix: /
      rewrite:
        uri: /cd/
      route:
        - destination:
            host: cd-server.argo.svc.cluster.local
            port:
              number: 80
---
